### PR TITLE
Picoserver

### PR DESCRIPTION
**Pull request by Terisback**
picoserver doesn't work with tcc, but apart from that it's cool

Tests:
`nedpals.vex.server`
image

`nedpals.vex.picoserver`
image

### CODE REVIEW

**Comment by gitMitos** [comment]
"cool" compare to golang fiber? :) or compare to php?

**Comment by alichraghi** [comment]
> "cool" compare to golang fiber? :) or compare to php?

I have done it before. Also available at https://www.techempower.com/. This is the fastest

**Comment by gitMitos** [comment]
> > "cool" compare to golang fiber? :) or compare to php?
> 
> I have done it before. Also available at https://www.techempower.com/. This is the fastest

I do not understand how you manage to do that. On my machine fiber shows ~160k+ req/sec
compiled pico server with "hi" as respond showing 6k at best and after few test - it drops to 1.2k: 
wrk -c200 -t200 -d60 -H 'Accept-Encoding: gzip' http://localhost:6789/ --latency
Running 1m test @ http://localhost:6789/
  200 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   102.83ms  147.40ms   1.84s    94.78%
    Req/Sec    14.31     16.86   101.00     93.94%
  Latency Distribution
     50%   80.31ms
     75%  102.08ms
     90%  181.04ms
     99%  938.80ms
  75464 requests in 1.00m, 9.86MB read
  Socket errors: connect 0, read 14, write 0, timeout 133
Requests/sec:   1255.75
Transfer/sec:    168.01KB
   
fiber: wrk -c200 -t200 -d60 -H 'Accept-Encoding: gzip' http://localhost:3000/hi --latency
Running 1m test @ http://localhost:3000/hi
  200 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    12.09ms   40.79ms 538.79ms   96.64%
    Req/Sec   834.34      1.54k   37.87k    88.19%
  Latency Distribution
     50%    1.22ms
     75%    9.94ms
     90%   23.59ms
     99%  244.28ms
  9633553 requests in 1.00m, 1.06GB read
Requests/sec: 160291.70
Transfer/sec:     18.04MB

**Comment by Terisback** [comment]
@gitMitos 
fiber is multithreaded
pico is not (now)

**Pull request merged**
